---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.4.2
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python}
from scipy import *
import numpy as np
import matplotlib.pyplot as plt
import PlanktonSignaling.basics as PS
import PlanktonSignaling.Deposition as DP
import PlanktonSignaling.PlottingMethods as PM
import profile
import copy
from numpy.fft import fftfreq, fftshift, fft2
# %matplotlib notebook

# #%load_ext Cython
```

# Figure 9

This will show the evolution of a 2D simulation, as described by the PDE system

$$ c_t = d_1 \Delta c - d_2 c + f(c) \rho$$

$$ \rho(\mathbf{x}, t) = \int_0^{2\pi} \psi(\mathbf{x}, \theta, t) \, d\theta$$ 

$$ \psi_t = - \mathbf{e}_{\theta} \cdot \nabla \psi - \frac{1}{2} \left[ 1 - \frac{ \nabla c \cdot \mathbf{e}_{\theta}}{\sqrt{\left(\nabla c \cdot \mathbf{e}_{\theta}\right)^2 + \delta^2 }}\right]  \psi + \frac{1}{4\pi} \int_0^{2\pi} \left[ 1 - \frac{ \nabla c \cdot \mathbf{e}_{\theta}}{\sqrt{\left(\nabla c \cdot \mathbf{e}_{\theta}\right)^2 + \delta^2 }}\right] \psi(\mathbf{x}, \theta', t) \, d \theta'$$

We solve $c$ explicitly using a Crank-Nicolson method, but we model $\rho$ as a discrete number of plankton and evolve them individually. Please see the paper for exact scheme we utilize.  

The simulation will take over 7 hours, so we sugest utilizing an HPC to replicate these.

The variables for the 2D system include:

depFcn - The deposition function from PlanktonSignaling.Deposition that will be performing the autochemotaxis. You have currently three option of constantDep, atanDep, and linAtanDep (see Figure 3 or /PlanktonSignaling/Deposition for more info)

L - Length of the spatial regime in $x$ and $y$, $[0,L] \times [0,L]$. 

d1 - the diffusion rate for the chemical 

d2 - the decay rate for the chemical 

N - the number of nodes for the chemical mesh ($N \times N$) 

Const - constant for the standard deviation for the autochemotaxis process (the width of Gaussian)

k - the timestep for the temporal mesh 

num - Number of plankton to simulate in the simulation

$c_0$ - initial constant solution for $c$

delta - for the approximation of $\text{sgn}(c_x)\approx \dfrac{c_x}{\sqrt{c_x^2 + \delta^2}}$

Parameters for $f(c)$:

depMaxstr - the maximum output of chemical in the system for the plankton 

depThreshold - the amount of chemical to activate the 'switch' in the deposition functions

depTransWidth - the relaxation parameter for the smoothness of the 'switch' deposition functions

```{python}
meshsize = 100 #Chemical Mesh size
numb = 400**2 #Number of plankton in simulation
LL = 10 #Length of domain [0,L] x [0,L]
dt = 0.02 #Time-stepping size
TotalTime = 20 #Total time 
simTime = int(TotalTime/dt) #Number of timesteps in order to achieve total Time 

Swimmers = PS.Plankton(DP.constantDep,d1=.1,d2=4,N = meshsize,depMaxStr=.01,
                           Const=3,L=LL,k=dt,delta=1e-3,depThreshold=0.012, 
                           depTransWidth=0.008, num = numb, c0=0.01)
Swimmers.CheckStability()

#Initial chemical background
def initial_conditions(x,y):
    return(0*x + Swimmers.c0)
```

```{python}
Swimmers.SetIC(initial_conditions)

lenn = int(np.sqrt(numb))
pos = np.zeros((numb,2))
vel = np.zeros((numb,2))
CHEM = np.zeros((simTime,meshsize,meshsize)) #preallocate the chemical 
POS = np.zeros((simTime,numb,2)) #preallocate the chemical 

#Place plankton down uniformly throughout the domain and give each a direction to travel initially
#Randomness can be added if desired.

i = 0
for l in range(0,lenn):
        for k in range(0,lenn):
                pos[i,:] = np.array([np.mod(k*(Swimmers.L*1/(lenn)) + 0.5*(Swimmers.L*1/(lenn)),Swimmers.L),
                                     np.mod(l*(Swimmers.L*1/(lenn)) + 0.5*(Swimmers.L*1/(lenn)),Swimmers.L)])
                th  = np.random.rand()*2*pi
                vel[i,:] = np.array([np.cos(th),np.sin(th)])
                i = i + 1

CHEM[0,:,:] = Swimmers.Meshed() 
POS[0,:,:] = pos 
```

```{python}
for k in range(1,simTime):
        Swimmers.UpdateSlice(Swimmers.scalar,pos,vel)
        CHEM[k,:,:] = Swimmers.Meshed()
        POS[k,:,:] = pos
```

```{python}
fig, axs = plt.subplots(nrows=3, ncols=5,figsize=(32,18),sharey='row')
Times = [0,.2,3,8,19.999]
fig.subplots_adjust(right=1)
fig.subplots_adjust(hspace=0.22, wspace=0.13)

#Plot Plankton
j = int(Times[0]/Swimmers.k)
xm, ym, ContoursSlice = PM.PartProj(Swimmers,POS[j],400)
cs1 = axs[0,0].pcolormesh(xm,ym,ContoursSlice,cmap='Reds')
cs1.set_clim(3,5)
axs[0,0].ticklabel_format(style='plain',axis='x')
axs[0,0].locator_params(nbins=3,axis='x')
axs[0,0].locator_params(nbins=3,axis='y')
axs[0,0].tick_params(labelsize=22)
axs[0,0].set_ylabel(r'$y$',size=27)
axs[0,0].set_xlabel(r'$x$',size=27)

j = int(Times[1]/Swimmers.k)
xm, ym, ContoursSlice = PM.PartProj(Swimmers,POS[j],400)
cs1 = axs[0,1].pcolormesh(xm,ym,ContoursSlice,cmap='Reds')
cs1.set_clim(3,5)
axs[0,1].ticklabel_format(style='plain',axis='x')
axs[0,1].locator_params(nbins=3,axis='x')
axs[0,1].locator_params(nbins=3,axis='y')
axs[0,1].tick_params(labelsize=22)
axs[0,1].set_xlabel(r'$x$',size=27)

j = int(Times[2]/Swimmers.k)
xm, ym, ContoursSlice = PM.PartProj(Swimmers,POS[j],400)
cs1 = axs[0,2].pcolormesh(xm,ym,ContoursSlice,cmap='Reds')
cs1.set_clim(3,5)
axs[0,2].ticklabel_format(style='plain',axis='x')
axs[0,2].locator_params(nbins=3,axis='x')
axs[0,2].locator_params(nbins=3,axis='y')
axs[0,2].tick_params(labelsize=22)
axs[0,2].set_xlabel(r'$x$',size=27)

j = int(Times[3]/Swimmers.k)
xm, ym, ContoursSlice = PM.PartProj(Swimmers,POS[j],400)
cs1 = axs[0,3].pcolormesh(xm,ym,ContoursSlice,cmap='Reds')
cs1.set_clim(3,5)
axs[0,3].ticklabel_format(style='plain',axis='x')
axs[0,3].locator_params(nbins=3,axis='x')
axs[0,3].locator_params(nbins=3,axis='y')
axs[0,3].tick_params(labelsize=22)
axs[0,3].set_xlabel(r'$x$',size=27)

j = int(Times[4]/Swimmers.k)
xm, ym, ContoursSlice = PM.PartProj(Swimmers,POS[j],400)
cs1 = axs[0,4].pcolormesh(xm,ym,ContoursSlice,cmap='Reds')
cs1.set_clim(3,5)
axs[0,4].ticklabel_format(style='plain',axis='x')
axs[0,4].locator_params(nbins=3,axis='x')
axs[0,4].locator_params(nbins=3,axis='y')
axs[0,4].tick_params(labelsize=22)
axs[0,4].set_xlabel(r'$x$',size=27)

cbar2 = fig.colorbar(cs1,ticks = [3,4,5],
                    ax=axs[0].ravel().tolist(),location='right',pad=0.01,shrink=0.8)
cbar2.update_ticks()
cbar2.ax.tick_params(labelsize=25)
cbar2.set_label(r'Plankton, $\rho$',size=30)
cbar2.ax.set_yticklabels([r'$3\overline{\rho}/4$',r'$\overline{\rho}$',r'$5\overline{\rho}/4$'])

#Plot Chemical

L = 0.0025
j = int(Times[0]/Swimmers.k)
cs1 = axs[1,0].pcolormesh(Swimmers.xm_periodic,Swimmers.ym_periodic,PM.BuildPeriodic(Swimmers,CHEM[j]),cmap='Blues')
cs1.set_clim(0.01-L,0.01+L)
axs[1,0].ticklabel_format(style='plain',axis='x')
axs[0,0].set_title(r'$t = {0}$',fontsize=40)
axs[1,0].locator_params(nbins=3,axis='x')
axs[1,0].locator_params(nbins=3,axis='y')
axs[1,0].tick_params(labelsize=22)
axs[1,0].set_ylabel(r'$y$',size=27)
axs[1,0].set_xlabel(r'$x$',size=27)

j = int(Times[1]/Swimmers.k)
cs = axs[1,1].pcolormesh(Swimmers.xm_periodic,Swimmers.ym_periodic,PM.BuildPeriodic(Swimmers,CHEM[j]),cmap='Blues')
cs.set_clim(0.01-L,0.01+L)
axs[1,1].ticklabel_format(style='plain',axis='x')
axs[0,1].set_title(r'$t = {0}$'.format(round(j*Swimmers.k,3)),fontsize=40)
axs[1,1].locator_params(nbins=3,axis='x')
axs[1,1].locator_params(nbins=3,axis='y')
axs[1,1].tick_params(labelsize=22)
axs[1,1].set_xlabel(r'$x$',size=27)

j = int(Times[2]/Swimmers.k)
cs = axs[1,2].pcolormesh(Swimmers.xm_periodic,Swimmers.ym_periodic,PM.BuildPeriodic(Swimmers,CHEM[j]),cmap='Blues')
cs.set_clim(0.01-L,0.01+L)
axs[1,2].ticklabel_format(style='plain',axis='x')
axs[0,2].set_title(r'$t = {0}$'.format(round(j*Swimmers.k)),fontsize=40)
axs[1,2].locator_params(nbins=3,axis='x')
axs[1,2].locator_params(nbins=3,axis='y')
axs[1,2].tick_params(labelsize=22)
axs[1,2].set_xlabel(r'$x$',size=27)

j = int(Times[3]/Swimmers.k)
cs = axs[1,3].pcolormesh(Swimmers.xm_periodic,Swimmers.ym_periodic,PM.BuildPeriodic(Swimmers,CHEM[j]),cmap='Blues')
cs.set_clim(0.01-L,0.01+L)
axs[1,3].ticklabel_format(style='plain',axis='x')
axs[0,3].set_title(r'$t = {0}$'.format(round(j*Swimmers.k)),fontsize=40)
axs[1,3].locator_params(nbins=3,axis='x')
axs[1,3].locator_params(nbins=3,axis='y')
axs[1,3].tick_params(labelsize=22)
axs[1,3].set_xlabel(r'$x$',size=27)

j = int(Times[4]/Swimmers.k)
cs2 = axs[1,4].pcolormesh(Swimmers.xm_periodic,Swimmers.ym_periodic,PM.BuildPeriodic(Swimmers,CHEM[j]),cmap='Blues')
cs2.set_clim(0.01-L,0.01+L)
axs[1,4].ticklabel_format(style='plain',axis='x')
axs[0,4].set_title(r'$t = {0}$'.format(round(j*Swimmers.k)),fontsize=40)
axs[1,4].locator_params(nbins=3,axis='x')
axs[1,4].locator_params(nbins=3,axis='y')
axs[1,4].tick_params(labelsize=22)
axs[1,4].set_xlabel(r'$x$',size=27)

cbar = fig.colorbar(cs2,ticks = [0.008,0.01,0.012],
                    ax=axs[1].ravel().tolist(),location='right',pad=0.01,shrink=0.8)
cbar.set_ticks([0.008,0.01,0.012])
cbar.update_ticks()
cbar.ax.tick_params(labelsize=25)
cbar.ax.set_yticklabels([r'$4\overline{c}/5$',r'$\overline{c}$',r'$6\overline{c}/5$'])
cbar.set_label(r'Chemical, $c$',size=30)

from numpy.fft import fftfreq, fftshift, fft2

#Plot Fourier Domaindef xy(r,phi):
def xy(r,phi):
    return r*np.cos(phi), r*np.sin(phi)

phis=np.arange(0,6.28,0.01)

#Input the norm of the most unstable wave number using the stability code
r = 6.096

freq = (len(Swimmers.xm)*2*pi/(Swimmers.L))*fftfreq(len(Swimmers.xm))

j = int(Times[0]/Swimmers.k)
omega = np.fft.fft2(CHEM[j])
field = axs[2,0].pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq), 
                            np.real(np.fft.fftshift(omega)),cmap='Greens')
flat=np.real(np.fft.fftshift(omega)).flatten()
flat.sort()
field.set_clim(0,flat[-1])
axs[2,0].set_ylim(-15,15)
axs[2,0].set_xlim(-15,15)
axs[2,0].plot( *xy(r,phis), c='k',ls='--',linewidth=2)
axs[2,0].locator_params(nbins=3,axis='x')
axs[2,0].locator_params(nbins=3,axis='y')
axs[2,0].tick_params(labelsize=22)
axs[2,0].set_ylabel(r'$k_2$',size=27,labelpad=-14)
axs[2,0].set_xlabel(r'$k_1$',size=27)

j = int(Times[1]/Swimmers.k)
omega = np.fft.fft2(CHEM[j])
field = axs[2,1].pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq), 
                            np.real(np.fft.fftshift(omega)),cmap='Greens')
flat=np.real(np.fft.fftshift(omega)).flatten()
flat.sort()
field.set_clim(0,flat[-2])
axs[2,1].set_ylim(-15,15)
axs[2,1].set_xlim(-15,15)
axs[2,1].plot( *xy(r,phis), c='k',ls='--',linewidth=2)
axs[2,1].locator_params(nbins=3,axis='x')
axs[2,1].locator_params(nbins=3,axis='y')
axs[2,1].tick_params(labelsize=22)
axs[2,1].set_xlabel(r'$k_1$',size=27)

j = int(Times[2]/Swimmers.k)
omega = np.fft.fft2(CHEM[j])
field = axs[2,2].pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq), 
                            np.real(np.fft.fftshift(omega)),cmap='Greens')
flat=np.real(np.fft.fftshift(omega)).flatten()
flat.sort()
field.set_clim(0,flat[-2])
axs[2,2].set_ylim(-15,15)
axs[2,2].set_xlim(-15,15)
axs[2,2].plot( *xy(r,phis), c='k',ls='--',linewidth=2)
axs[2,2].locator_params(nbins=3,axis='x')
axs[2,2].locator_params(nbins=3,axis='y')
axs[2,2].tick_params(labelsize=22)
axs[2,2].set_xlabel(r'$k_1$',size=27)

j = int(Times[3]/Swimmers.k)
omega = np.fft.fft2(CHEM[j])
field = axs[2,3].pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq), 
                            np.real(np.fft.fftshift(omega)),cmap='Greens')
flat=np.real(np.fft.fftshift(omega)).flatten()
flat.sort()
field.set_clim(0,flat[-2])
axs[2,3].set_ylim(-15,15)
axs[2,3].set_xlim(-15,15)
axs[2,3].plot( *xy(r,phis), c='k',ls='--',linewidth=2)
axs[2,3].locator_params(nbins=3,axis='x')
axs[2,3].locator_params(nbins=3,axis='y')
axs[2,3].tick_params(labelsize=22)
axs[2,3].set_xlabel(r'$k_1$',size=27)

j = int(Times[4]/Swimmers.k)
omega = np.fft.fft2(CHEM[j])
field = axs[2,4].pcolormesh(np.fft.fftshift(freq),np.fft.fftshift(freq),
                            np.real(np.fft.fftshift(omega)),cmap='Greens')
flat=np.real(np.fft.fftshift(omega)).flatten()
flat.sort()
field.set_clim(0,flat[-2])
axs[2,4].set_ylim(-15,15)
axs[2,4].set_xlim(-15,15)
axs[2,4].plot( *xy(r,phis), c='k',ls='--',linewidth=2)
axs[2,4].locator_params(nbins=3,axis='x')
axs[2,4].locator_params(nbins=3,axis='y')
axs[2,4].tick_params(labelsize=22)
axs[2,4].set_xlabel(r'$k_1$',size=27)
cbar = fig.colorbar(field,ticks = [0,flat[-2]],
                    ax=axs[2].ravel().tolist(),location='right',pad=0.01,shrink=0.8)
cbar.set_ticks([0,flat[-2]])
cbar.update_ticks()
cbar.ax.tick_params(labelsize=25)
cbar.ax.set_yticklabels([r'$0$',r'Max'])
cbar.set_label(r'$\widetilde{E}(\mathbf{k})$',size=32)
plt.show()
#plt.savefig('../Final_Figures/Fig9')
```

```{python}

```
